language: python
python:
  - "2.7"


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev libgsl0ldbl libgsl0-dbg
  - sudo apt-get install -y swig


install: python setup.py install
